### PR TITLE
Apple homepage1

### PR DESCRIPTION
**Pull request by mertcihankurel**
## İn this project:
1-) Covered background image.
2-) Added navbar, includes icons.
3-) Entire page fixed with zero margin and padding.
4-) Header elements centered by width styling.
5-) Added lighter font size to header elements.
6-) İnput background changed as original.
7-) Given width to "h" elements.
8-) Given 100% width to aside section.
9-) Unexpected empty lines removed.

### CODE REVIEW

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Status: Changes required 🛑

## Hello @mcihadkurel 👋! You have done a remarkable job making this project. It's one of the best projects I have seen 💯. It looks so professional 😎!

### But there are a couple of minor issues that we need to work on.

- Try to match the background color of the search field in the navbar with the original.

#### Clone
image

#### Original
image

- Decrease the width of the navbar to match the original.

- Decrease the width of the `text` class to match the original.

#### Clone
image

#### Original
image

- This section must take the full width of the screen.

image

#### Original
image

Apply these changes request another review.

Happy coding 👨‍💻

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status requires changes :recycle: 
## Hello guys, great job for what you have done already but in order to allow me to review your project your need to fix all the errors in stickler, please do that and request another code review:
image

## Happy Coding :tophat: 
_If you are stuck or you have any questions don't hesitate to contact me on slack_

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status requires changes :recycle: 
## Great job so far guys :100: :clap:, you are almost there :checkered_flag:  but in order to make your project approved you need to make just a couple of changes. :hammer: :toolbox: :wrench: 
- [ ] as mentioned by the previous TSE this section should take the whole screen:
image

- [ ] Minimize the width of the text inside the main section, give it like around 75% and center the container:
image

- [ ] match the background color of the navbar with the original.

### Please make the required changes before requesting a new code review.
## Happy Coding :tophat:

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status requires changes :recycle: 
## Still the same thing please contact me on slack.
image

## Happy coding :tophat:

**Review by elmejdki — APPROVED** [review]
# status approved :heavy_check_mark: 
## Great job guys :clap:, thank you @mcihadkurel for making the required changes.

now you can merge to master your project is approved.

# Happy Coding :tophat:

**Pull request merged**
